// Exports data/profile.json into public/data/content.js so the site can be
// deployed as 100% static hosting (GitHub Pages, Netlify, Vercel, etc.)
// Usage: npm run export
const fs = require("fs");
const path = require("path");
const { publicObject } = require("../lib/privacy");
const { readProfile } = require("../lib/storage");

const profile = readProfile();
const output = [
  "// ============================================================",
  "//  AUTO-GENERATED by `npm run export`. Do not edit by hand.",
  "//  Edit data/profile.json (or the /admin panel) and re-run export.",
  "// ============================================================",
  "",
  "window.SITE_CONTENT = " + JSON.stringify(publicObject(profile), null, 2) + ";",
  "",
].join("\n");

const file = path.join(__dirname, "..", "public", "data", "content.js");
fs.writeFileSync(file, output, "utf8");
console.log("Exported public profile -> public/data/content.js");
console.log("(Private fields are excluded from this static build.)");